### ISSUE TITLE
Possible memory leak (or V8's GC problem?)

### ISSUE THREAD

**Issue by rinsuki** [denosaurs/deno_lz4#1]
Every time I call `decompress`, the memory usage of the Deno process increases a little bit and when it gets to about 2GB it crashes.

## reproduce script

**CAUTION: The following programs will consume more than 2 GB of your computer's memory when run. Be careful.**

```typescript
import { compress, decompress } from "https://deno.land/x/lz4@v0.1.0/mod.ts";
const text = new TextEncoder().encode("X".repeat(1024 * 1024 * 16));
const compressed = compress(text)

var c = 0
while(true) {
	c++
	console.log(c)
	decompress(compressed)
}
```

## expected result

```
$ deno run ./deno-lz4-stress-test.ts 
1
2
3
(The numbers continue to be incremented infinitely without crashing)
```

## actual result

```
$ deno run ./deno-lz4-stress-test.ts 
1
2
(... trimmed ...)
125
126
error: Uncaught RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at B (https://deno.land/x/lz4@v0.1.0/wasm.js:2:12360)
    at lz4_decompress (https://deno.land/x/lz4@v0.1.0/wasm.js:2:12740)
    at decompress (https://deno.land/x/lz4@v0.1.0/mod.ts:41:10)
    at file:///path/to/deno-lz4-stress-test.ts:9:17
    at <anonymous> (<anonymous>)
```

The "126" is the number of times the script succeeds in decompressing, and in my environment it's the same value no matter how many times I run this script.

## my environment

```
$ deno --version
deno 1.0.3
v8 8.4.300
typescript 3.9.2
```

**Comment by rinsuki** [comment]
After adapting the patch, it appears to be working fine. Thank you so much! @eliassjogreen
